name: Tests and GH release

env:
  FORCE_COLOR: 1

on:
  push:
  pull_request:
    branches:
      - master
      - main
jobs:
  # test_linux:
  #   name: ${{ matrix.os }} (${{ matrix.browser }})
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os: [ubuntu-20.04]
  #       # os: [ubuntu-18.04, ubuntu-20.04]
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 14
  #     - uses: microsoft/playwright-github-action@v1
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Run tests
  #       run: npm test
  # test_win:
  #   name: "Windows"
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 14
  #     - uses: microsoft/playwright-github-action@v1
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Run tests
  #       run: npm test
  tag:
    name: "Publishing tag"
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    # needs: 
    #   - test_linux
    #   - test_win
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Read node from package.json
        uses: culshaw/read-package-node-version-actions@v1
        id: package-node-version
      - name: Publishing tag
        id: publish_tag
        uses: tvdias/github-tagger@v0.0.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.package-node-version.outputs.version }}
          commit-sha: ${{ github.sha }}
